name: Strady_AlgoReconnaissance
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - ultralytics=8.4.156
  - torchvision=0.28.0
  - pandas=3.0.6
  - wandb=0.30.0
  - python-dotenv=1.2.3
