# Fichier de configuration pour le transfer learning du modèle YOLOv26 Nano déjà entrainé sur le dataset DeepDarts) sur nos données.
# J'ai utilisé cette config pour le premier transfer learning.

data:
  path: "datasets/strady_yolo/data.yaml"
  dataset_version: "perso - 1157 photos de David"

train:
  seed: 0 # Pour avoir une expérience reproductible -> cependant sur mac j'ai un avertissement que certaines opérations ne sont pas déterministes, donc ça ne garantit pas une reproductibilité parfaite. Donc je coupe pour de meilleures perf. (j'ai ajouté dans train un champ "deterministic=False" pour désactiver la reproductibilité et gagner en vitesse).
  epochs: 300 # Je règle sur 300 car c'est conseillé par ultralytics pour YOLO26. DeepDarts avait mis 100 pour YOLOv4-tiny.
  # batch_size: 16 # Choisi par DeepDarts pour YOLOv4-tiny.
  batch_size: 32 # Pour mon MBP M1 MAX je vais booster le batch_size.
  # batch_size: -1 # YOLO26 va choisir automatiquement le batch_size maximal possible selon la VRAM disponible. Je teste. UPDATE -> MARCHE PAS SUR MAC MAIS QUE SUR LES GPU NVIDIA MACHIN.
  # lr: 0.001 # Je dégage le lr dépassé de DeepDarts pour YOLOv4-tiny. YOLO26 gère le lr automatiquement maintenant. Si ça va pas je choisirai spécifiquement AdamW comme optim. avec un lr.
  patience: 25 # Si le modèle n'améliore pas sa performance sur la validation pendant 25 epochs, l'entrainement s'arrête.
  val: true
  project: "strady" # Dossier de sortie pour les runs d'entrainement.
  name: "strady_yolo_run" # Nom du run en local et précisé également à wandb

aug:
  # Équivalents YOLO26 des augmentations DeepDarts
  flip_lr_prob: 0.0 # Probabilité miroir horizontal (fliplr)
  flip_ud_prob: 0.0 # Probabilité miroir vertical (flipud)
  rot_step: 0.0 # Rotation en degrés (degrees)
  jitter_max: 0.0 # Translation fractionnelle (translate)
  mosaic: 0.0 # Désactivé. Par défaut YOLO l'active. Ici je crois comprendre que c'est nul car il va mélanger des parties d'images ensemble, le modèle a besoin de l'image globale.
  perspective: 0.0 # DeepDarts l'ont fait eux même (le warping) via une fonction python spécifique. Nous on va déjà essayer avec l'intégration native de YOLO26. On verra si c'est suffisant. (Ils avaient besoin de ça surtout pour la reconnaissance des points de calibrage de la cibls)

model:
  weights_path: "runs/detect/strady/deepdarts_d1_yolo_run/weights/best.pt"
  input_size: 800
